### ISSUE TITLE
Plugin for 1.x to 5.x

### ISSUE THREAD

**Issue by amazinganshul** [elastic/elasticsearch-migration#100]
Looking at the timelines for the support that will be there for 2.x version(till next year February), also we are using version 1.7.4 and are analyzing on moving to 2.x or 5.x, wanted to know if there is any plugin for checking migration from 1.x to 5.x?

**Comment by clintongormley** [comment]
No there isn't, and you can't upgrade your indices directly from 1.x to 5.x.  You will need to reindex them in 2.x first.  One alternative is to go to 5.x and use reindex-from-remote to import your indices from the 1.x cluster.
