### ISSUE TITLE
Shall I use this plugin to migrate from 2.1.1 to 5.2.0

### ISSUE THREAD

**Issue by fizerkhan** [elastic/elasticsearch-migration#101]
Will this plugin support migration from Elasticsearch 2.1.1 to 5.2.0?

**Comment by clintongormley** [comment]
yes

**Comment by fizerkhan** [comment]
But `Reindex Helper` and `Deprecation Logging` does not work for me.

**Comment by clintongormley** [comment]
As the instructions say, for that you need to upgrade to 2.4

**Comment by fizerkhan** [comment]
Thanks @clintongormley
