### ISSUE TITLE
Provide direct reference to advisory notes on "moved to the archived namespace" 

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-migration#104]
Feedback from users in the field:

For advisory notes against settings that are now superseded by another setting, it will be helpful to have this information directly in the migration plugin response.  Currently, there is a [i] icon that links to the high level settings changes breaking doc.  For setting issues for the other "color" settings failures, we do provide the renamed setting with the migration results.  So it will be nice to provide similar text in the migration plugin results, or have the [i] icon link to the specific anchor on the settings page (instead of generically linking to the top level settings page).

**Comment by clintongormley** [comment]
This is basically impossible to do - all unknown settings are archived.
