### ISSUE TITLE
Elasticsearch-migration helper for version 2.2

### ISSUE THREAD

**Issue by rbagul** [elastic/elasticsearch-migration#105]
Hi,

It is been mentioned that this plugin is available for only versions 2.3 and 2.4.
We have Elasticsearch 2.2 and want to upgrade it to 5.x. Which version of Elasticsearch-migration plugin we can use. 

Thanks,
Rakesh

**Comment by dadoonet** [comment]
You need to update to 2.4 first.

**Comment by clintongormley** [comment]
The reindex tool and deprecation log only works in 2.3/2.4 (but i'd recommend 2.4 as it has a host of improvements)

**Comment by rbagul** [comment]
Sure, Thanks!
