### ISSUE TITLE
The plugin does not install

### ISSUE THREAD

**Issue by blazerguns** [elastic/elasticsearch-migration#106]
aruns-MBP:elasticsearch-2.4.1 varun$ bin/plugin install ~/Downloads/elasticsearch-migration-2.0.4.zip 
bin/plugin: line 113: /Library/Internet: No such file or directory
Varuns-MBP:elasticsearch-2.4.1 varun$ 

This is OSX 10.12 running elasticsearch 2.4.1 as unzipped tarball from your site. I run elasticsearch using the launchctl script.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <true/>
    <key>Label</key>
    <string>com.elasticsearch2</string>
    <key>ProgramArguments</key>
    <array>
      <string>/devel/elasticsearch-2.4.1/bin/elasticsearch</string>
      <string>-DXmx4g</string>
      <string>-DXms4g</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
      <key>ES_JAVA_OPTS</key>
      <string>-Xss400000</string>
      <key>ES_HEAP_SIZE</key>
      <string>4G</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>/usr/local/var</string>
    <key>StandardErrorPath</key>
    <string>/dev/null</string>
    <key>StandardOutPath</key>
    <string>/dev/null</string>
  </dict>
</plist>
```

**Comment by blazerguns** [comment]
This does not work even with ./bin/plugin install https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.4/elasticsearch-migration-2.0.4.zip

**Comment by blazerguns** [comment]
I found the issue. Its more a plugin script issue. In my box, JAVA_HOME is/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

It looks like the script does not handle Internet<space>Plug-Ins. It should be Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

**Comment by clintongormley** [comment]
This is a bug for Elasticsearch (note, already fixed in 5.x)
