### ISSUE TITLE
No warning given for environment variables that are no longer supported

### ISSUE THREAD

**Issue by dannygoulder** [elastic/elasticsearch-migration#108]
`Error: Could not start Service[elasticsearch-instance-01]: Execution of '/sbin/service elasticsearch-01 start' returned 1: Starting elasticsearch-01: Error: encountered environment variables that are no longer supported
Use jvm.options or ES_JAVA_OPTS to configure the JVM
ES_HEAP_SIZE=4g: set -Xms4g and -Xmx4g in jvm.options or add "-Xms4g -Xmx4g" to ES_JAVA_OPTS
[FAILED]
`

Didn't get any prior warning of this when running the migration helper

**Comment by clintongormley** [comment]
There's no way for the migration helper to detect environment variables - it is best effort only, there are many other things that the migration helper cannot detect.
