### ISSUE TITLE
Filter based on what will or will not allow the cluster to start 

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-migration#110]
Having an option to filter based on what will or will not allow the cluster to start will be helpful for admins.

**Comment by clintongormley** [comment]
Those items should show up as red - this isn't sufficient?

**Comment by ppf2** [comment]
If all the breaking changes (at least the ones detectable via our API calls) that will cause the node not to start up are covered by "red", we should be good here :)
