### ISSUE TITLE
Deprecation Logging

### ISSUE THREAD

**Issue by abhiCR7** [elastic/elasticsearch-migration#111]
This tool supports both 2.3.x and 2.4.x, but it seems deprecated logging is not supported on 2.3.x.
I'm getting message
`Deprecation logging is available in Elasticsearch 2.4.x only.`
If that is so, then do i need to upgrade to 2.4.x first? If yes, it would be really helpful if anyone can point me to instructions for the same.
Thanks.

**Comment by clintongormley** [comment]
Yes you need to upgrade. See https://www.elastic.co/guide/en/elasticsearch/reference/2.4/setup-upgrade.html

**Comment by abhiCR7** [comment]
Thanks @clintongormley
