### ISSUE TITLE
reindex all indices

### ISSUE THREAD

**Issue by tomryanx** [elastic/elasticsearch-migration#113]
I have a large number of indices. It would be really nice to not have to click "reindex" a few thousand times!

Any chance of a "reindex all" button?

**Comment by mountassirIbrahim** [comment]
+1. It's heavy to reindex manually each index. Is there any way to reindex all indices ?

Thanks.

**Comment by clintongormley** [comment]
there isn't a way to do it i'm afraid, and we won't be releasing any more versions of this migration plugin.  The new migration plugin will be available in Kibana X-Pack Basic
