### ISSUE TITLE
error when migration plugin is executed

### ISSUE THREAD

**Issue by dhireng** [elastic/elasticsearch-migration#116]
I get the following error when I run the migration plugin: Mapping definition for [_timestamp] has unsupported parameters. 
Is reindexing the only option?

**Comment by clintongormley** [comment]
Hi @dhireng 

I don't know what version you're using, nor what you're trying to do when you get that message, but I'm going to assume that you're trying to reindex an index and you get that message when it tries to create the new index.

In that case, yes, you need to edit the mapping yourself.  There's a link to click which will give you the instructions to run manually.  You can copy and paste those, then edit them to fix the mappings and run the commands manually
