### ISSUE TITLE
API / URL to call check

### ISSUE THREAD

**Issue by martbhell** [elastic/elasticsearch-migration#13]
Hi, 

This plugin looks really useful.

I would like to be able to run a check of all the indices regularly.
Reason: To find if someone is making bad choices in field names.

// mart

**Comment by clintongormley** [comment]
Hi @martbhell 

We needed this to work across all 1.x versions of Elasticsearch, so the easiest thing to do was to make it a site plugin in Javascript.  The downside of course is that it needs a browser to run in... Not sure how easy it'd be to make it into something you could call from (eg) a cron script.

I view the plugin as being useful when you start the migration to 2.0.  Of course, once you're on 2.0 you'll be prevented from making the mistakes that the plugin highlights (eg conflicting field names).

Perhaps you have some other ideas?

**Comment by clintongormley** [comment]
Oh also, in 2.0 we have deprecation logging.  So when we deprecate something going forward, we'll log the fact that you're using deprecated functionality. This will make it easier to automatically track problems that need fixing.

**Comment by martbhell** [comment]
Hi @clintongormley,

Don't know if it's hard or easy either. Anyway output should of course be in something that's easy(tm) to parse :)

I'll just run manually for now. Hopefully without making too many similar mistakes between fixing it and doing the migration.

**Comment by clintongormley** [comment]
Closing. Until this plugin is moved to a Kibana plugin that can run in node.js, this isn't something that can be supported
