### ISSUE TITLE
Links to documentation

### ISSUE THREAD

**Issue by jlecour** [elastic/elasticsearch-migration#25]
Hi,

I'm planning a migration to 2.0 and this plugin is really useful.

It shows me a handful of things that won't work anymore but doesn't say much why the change was introduced, what should be done…
Links to documentation, blog posts of even commits or PRs would be very helpful.

Thanks.

**Comment by jlecour** [comment]
Thanks @clintongormley for such a quick fix.

I've updated to v0.06 and now I get the (i) with the link after each passing (green) test, but not after the blue ones.

![elasticsearch-migration-test-link](https://cloud.githubusercontent.com/assets/5142/9561332/fc364972-4e40-11e5-8139-bcf6dfc364cf.png)

Did I do something wrong?

**Comment by clintongormley** [comment]
Doh - I'm an idiot. Pushing a fix now

**Comment by clintongormley** [comment]
thanks for reporting @jlecour - 0.07 fixes this
