### ISSUE TITLE
Detect use of deprecated `index_name`

### ISSUE THREAD

**Issue by nezda** [elastic/elasticsearch-migration#31]
https://github.com/elastic/elasticsearch/issues/6677 - deprecated in 1.5 https://www.elastic.co/guide/en/elasticsearch/reference/1.5/mapping-core-types.html

**Comment by clintongormley** [comment]
Hi @nezda 

This is already detected: https://github.com/elastic/elasticsearch-migration/blob/master/js/index_mappings_fields/checks.js#L9
