### ISSUE TITLE
Errs out on empty cluster with Shield

### ISSUE THREAD

**Issue by alexbrasetvik** [elastic/elasticsearch-migration#33]
An empty cluster should be trivially updatable. However, if Shield is enabled, the `_aliases`-lookup will err `IndexMissingException[[_all] missing]` instead of returning an empty list, resulting in an error.

**Comment by clintongormley** [comment]
This is a problem with Shield: https://www.elastic.co/guide/en/shield/current/limitations.html#_changes_in_index_wildcard_behavior

I don't see how to fix this in the migration plugin.

Fortunately, if you have an empty cluster, upgrading shouldn't be too tricky :)
