### ISSUE TITLE
Migration Checker can appear to hang when checking remote clusters without HTTPS support

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch-migration#37]
The migration checker can appear to hang when checking a remote cluster without `HTTPS` enabled. This happens when the web browser blocks `HTTP` requests  to the remote cluster if the migration tool itself was accessed via `HTTPS`. 

error from browser console:

```
Mixed Content: The page at 'https://es-mon.zmb.moc:9200/_plugin/migration/' was loaded
over HTTPS, but requested an insecure XMLHttpRequest endpoint 
'http://es-node1.zmb.moc:9200/'. This request has been blocked; the content must be 
served over HTTPS.
```

Migration tool access URL: `https://es-mon.zmb.moc:9200/_plugin/migration/`
Remote Cluster: `http://es-node1.zmb.moc:9200/`

Chrome 46.0.2490.80 (64-bit) and Safari 9.0 (10601.1.56.2)

**Comment by clintongormley** [comment]
Closed by de7e5027ec42ad5c3eb00ef1eb4a55fd11097ec4
