### ISSUE TITLE
Make the information for each index collapsable

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch-migration#4]
The information for each index can be very large. It would be useful if you could collapse each index so that you can easily get rid of indexes that you have dealt with rather than a lot of scrolling.
![screen shot 2015-05-21 at 14 30 34](https://cloud.githubusercontent.com/assets/236731/7749528/264fc16c-ffc6-11e4-84d3-9e4cced99bd4.png)

**Comment by clintongormley** [comment]
Output reformatted to be more concise, and defaults to showing failures only.

Closing
