### ISSUE TITLE
Strange mapping conflict found

### ISSUE THREAD

**Issue by slavag** [elastic/elasticsearch-migration#40]
I ran migration checker to see if I can move from ES 1.7.1 to 2.0 and got many mapping conflicts, one of them is that I have within same index 2 different types each one of them has same field : account and it's mapping is (both fields has exactly same mapping):

_type : string_
_index : not_analyzed_
_store : no_
_doc_values : true_

Here the exact mapping (Java) :

**Type A:**
....
.startObject("account") 
    .field("type", "string") 
    .field("index", "not_analyzed") 
    .field("store", "no") 
    .field("doc_values","true")
.endObject() 
....

**Type B:**
....
.startObject("account") 
    .field("type", "string") 
    .field("index", "not_analyzed") 
    .field("store", "no") 
    .field("doc_values","true")
.endObject()
....
They exactly the same, so, I don't see any conflict between two of them, but maybe I'm missing something.
Any advise ?
Thanks

**Comment by clintongormley** [comment]
Hi @slavag 

Could you upload the result of:

```
GET my_index/_mapping
```

thanks

**Comment by clintongormley** [comment]
No more feedback. Closing
