### ISSUE TITLE
2.0.0 doesn't support upgrading 1.7 indexes that require plugins

### ISSUE THREAD

**Issue by beiske** [elastic/elasticsearch-migration#42]
Users with 1.7 indexes that require custom plugins should upgrade directly to a version of ES that fixes elastic/elasticsearch#14828

**Comment by monowai** [comment]
Indeed. Be nice if this tool reported that fact - I failed to check this issue log until I'd spent an hour figuring it out the hard way.

**Comment by clintongormley** [comment]
This was fixed a long time ago, so I'll close
