### ISSUE TITLE
'Run checks now' doesn't work with text based browsers.

### ISSUE THREAD

**Issue by ThomasdOtreppe** [elastic/elasticsearch-migration#45]
Hi,

I can't really forward the ports to be able to connect to the different ElasticSearch instance we manage. So, I'm pretty much stuck with using text based browsers to check before doing migration.

I tried lynx, links2, links (and I might have tried w3m too) and none seem to be able to get past the main screen:

```
links2 http://localhost:9200/_plugin/migration
```

At the bottom, the first field is already filled (with http://localhost:9200) and the second field is blank (indices). I tried 'clicking' on 'Run checks now' with the second field empty or filled, and it always goes back to the migration page with all values reset.

Clicking on 'Breaking changes' works just fine.

**Comment by markwalkom** [comment]
Maybe having a file based output of the results would help?

**Comment by ThomasdOtreppe** [comment]
yes. If the API could be documented so we can use curl to interact with it, that would be awesome. Via JSON for example.

**Comment by ThomasdOtreppe** [comment]
To explain the situation, I have a bunch of nodes around the country connected to a main server via a VPN connection. The only way I can access them is sshing into the main server (that is also the VPN server) then sshing into the individual nodes. iptables rules are fairly restrictive on both server and nodes.

**Comment by clintongormley** [comment]
Unfortunately, this is heavily based on javascript - won't be able to support text-based browsers
