### ISSUE TITLE
misleading output when blocked by a proxy

### ISSUE THREAD

**Issue by ynux** [elastic/elasticsearch-migration#49]
We run our cluster behind a proxy which is allowing only specified requests (kibana and kopf read-only). This results in strange behaviour of the migration tool. It comes back red, marking all indices as closed. Some were closed, in fact. So I ran it with "Ignore closed indices". This resulted in a green migration tool, and it skipped all indexes. 
Another attempt with all indices opened had the same result. Only removing the proxy helped.
I suggest:
A - When the tool receives a HTML 404, it shows it;
B - A set of simple curl scripts checking for conflicts etc that can be run from the command line, for environments where people cannot change the proxy configuration.

**Comment by clintongormley** [comment]
> When the tool receives a HTML 404, it shows it;

This should work in the 2.x tool

> B - A set of simple curl scripts checking for conflicts etc that can be run from the command line, for environments where people cannot change the proxy configuration.

Given that the plugin is implemented in a significant amount of JS, it would not be trivial to replicate in curl.
