### ISSUE TITLE
Detect metadata fields with conflicting settings

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch-migration#50]
We currently have any configuration on metadata fields marked as a warning. However, if the metadata field is configured differently across types, this will block upgrading, and should be marked as such in the migration check.

See https://discuss.elastic.co/t/upgrade-from-1-7-x-to-2-2-0--timestamp-mapping-issue/41894.

**Comment by clintongormley** [comment]
Closing as 1.x is no longer supported
