### ISSUE TITLE
2.x - Node Settings - index.queries.cache.type can no longer be set in the config file

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch-migration#55]
@clintongormley ,

Getting a number of errors running 2.x migration checker on 2.3.0.  Not sure if they are valid or not.
- `index.queries.cache.type can no longer be set in the config file` - not sure where this is coming from.  This is not set in `elasticsearch.yml`
- shield config is all marked as invalid/unknown

![screen shot 2016-04-25 at 12 00 31 pm](https://cloud.githubusercontent.com/assets/4387023/14790076/a0764fce-0add-11e6-96d0-f1ded3020a63.png)

**Comment by clintongormley** [comment]
Closed by 447fe04eb30eea7c9197698e51d8fcdba544b820 and f5df3db4ae06661be89499335c5249466e4cd757
