### ISSUE TITLE
Plugin doesn't detect _id field for .percolator type documents

### ISSUE THREAD

**Issue by ayushsangani** [elastic/elasticsearch-migration#56]
I am upgrading ES from 1.6.1 to 2.1.2 and it seems that migration plugin is just giving "advisory" note if there is `_id` field present in `.percolator` document. Instead it should throw a red signal "You cannot upgrade without fixing this problem". 
Created from discussion group: https://discuss.elastic.co/t/snapshot-restore-failing-while-restoring-indexes-from-es-1-6-1-to-es-2-1-2/49197

Let me know if any other information or help is required.

**Comment by clintongormley** [comment]
Closed by e9ba0c159cb2686bb5989de4371c840fdb320439
