### ISSUE TITLE
Node attributes move to attr namespace check issue

### ISSUE THREAD

**Issue by nul** [elastic/elasticsearch-migration#57]
Running the check on my 2.3.0 cluster, I initially got this message:

> node.max_local_storage_nodes should be rewritten as node.attr.max_local_storage_nodes
> node.physicalServer should be rewritten as node.attr.physicalServer

I made the configuration change and re-ran the check, and as a result I got this:

> node.attr.max_local_storage_nodes should be rewritten as node.attr.attr.max_local_storage_nodes
> node.attr.physicalServer should be rewritten as node.attr.attr.physicalServer

Looks like the check doesn't correctly identify attributes already part of the attr namespace.

**Comment by clintongormley** [comment]
thanks for the report @nul - this is now fixed in https://github.com/elastic/elasticsearch-migration/commit/a06950c4a02adae088cd0757f446e8cd577b1886

Just a note: you shouldn't rename these settings on your 2.x cluster, only when moving to 5.x

**Comment by clintongormley** [comment]
Oh also, the node.max_local_storage_nodes -> node.attr.max_local_storage_nodes advice was incorrect.  I've fixed that as well.  Will release a new version of the checker in the near future
