### ISSUE TITLE
Migration Plugin Installation

### ISSUE THREAD

**Issue by JoyceBabu** [elastic/elasticsearch-migration#64]
The documentation for installing the migration plugin says

> To install, run the following command in your Elasticsearch home directory on a *nix system:
> 
> ./bin/plugin install https://github.com/elastic/elasticsearch-migration/releases/download/v2.0-alpha3/elasticsearch-migration-2.0-alpha3.zip

But the plugin installed in v5.0.0-alpha4 is at `./bin/elasticsearch-plugin`

When I run `./bin/elasticsearch-plugin install`, I am getting the error

> -> Downloading https://github.com/elastic/elasticsearch-migration/releases/download/v2.0-alpha3/elasticsearch-migration-2.0-alpha3.zip
> ERROR: `elasticsearch` directory is missing in the plugin zip

**Comment by clintongormley** [comment]
@JoyceBabu the documentation states that this plugin is intended to be installed on ES 2.3.x, not on ES 5.x.  It's a checkup BEFORE you upgrade to 5.x
