### ISSUE TITLE
End-users vs. cluster operators

### ISSUE THREAD

**Issue by alexbrasetvik** [elastic/elasticsearch-migration#66]
It'd be nice if the migration dashboard could have a mode to disable checks that users of the clusters shouldn't need to care about - defaulting to the current behaviour of checking everything.

For Cloud, we don't need users to worry about node-level settings that we'll be ensuring are correct, so it'd be nice to hide those.

**Comment by clintongormley** [comment]
I'll add a `?cloud` switch which will disable the checks that are not relevant for cloud
