### ISSUE TITLE
Should we flag safeguards that have been exceeded?

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch-migration#67]
For example, if a user has a large shard count (https://github.com/elastic/elasticsearch/pull/17396), a large number of fields in their mapping (https://github.com/elastic/elasticsearch/pull/17357), a large number of nested fields (https://github.com/elastic/elasticsearch/issues/14983), or a very high depth in their mappings (https://github.com/elastic/elasticsearch/pull/17400), they may switch over to 5.0 and have unexpected results.  We could detect this in the migration assistant prior to the upgrade and provide some help.

**Comment by clintongormley** [comment]
Fixed in 2.0.0-beta1
