### ISSUE TITLE
Update breaking changes URL

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch-migration#68]
Currently we link to https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_settings_changes.html but this has moved to https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_settings_changes.html without a redirect.  We should update this to reflect the correct location

**Comment by clintongormley** [comment]
Closed by 69d87c7f2a119b805042abf4a7010a786a4da407
