### ISSUE TITLE
Make watcher thread_pool settings check blue in migration plugin

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-migration#72]
I will suggest making the watcher thread_pool settings check blue (always).  

In this case, I haven't set any watcher specific thread pool settings on 2.x but the migration plugin is marking the following as red:

![image](https://cloud.githubusercontent.com/assets/7216393/19340685/05ab996c-90df-11e6-843d-2fb7bce8949b.png)

And this is because the Watcher plugin has coded in its own node settings for the watcher thread pool (type=fixed, size=5*# of cores, queue_size=1000) when there is no explicit node level settings defined by the end user.

It will probably be difficult to differentiate if the setting is set by the Watcher plugin itself, or by an end user via the nodes settings, so we may want to make this check blue as an advisory note and let the user know that if they happen to have set these settings at the node level themselves, they will have to switch to the new setting names with xpack references on 5.x, but if they haven't set these directly at the node level, they can ignore this advisory note, etc..

**Comment by clintongormley** [comment]
Closed
