### ISSUE TITLE
False positive detected on "transform" field

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-migration#73]
![image](https://cloud.githubusercontent.com/assets/7216393/19341695/6283324a-90e3-11e6-8ea6-d924433ffa33.png)

It looks like it is treating the "transform" field under properties as using the removed source transform feature when it should only be checking for "transform" directly under the document type level.

![image](https://cloud.githubusercontent.com/assets/7216393/19341679/4f90050a-90e3-11e6-92d2-0f1de66dc9ad.png)

**Comment by clintongormley** [comment]
Fixed
