### ISSUE TITLE
Report plugin install changes in red, not blue?

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-migration#75]
![image](https://cloud.githubusercontent.com/assets/7216393/19371331/ed3e5724-9166-11e6-9f54-6696b4c64f62.png)

It is more appropriate to mark the splitting of the single Azure/AWS/GCE plugin into 2 plugins as red so that users can take action to update any puppet/chef/automation script to reference a different plugin name moving forward.

Similarly, maybe also do the same for watcher/shield/marvel-agent/graph/license -> x-pack?

**Comment by eskibars** [comment]
Right now, renamed plugins show in blue and removed plugins show in yellow.  I'm not sure whether red or yellow is more appropriate here.  It seems like a yellow situation to me for both of them, but I don't know that the levels are really so discretely defined.

**Comment by ppf2** [comment]
Oh yah I forgot there's such thing as yellow.  So yellow fits too, better than blue (because the blue description text says no action needed) :)

**Comment by clintongormley** [comment]
Changed to yellow
