### ISSUE TITLE
Migration plugin recommends invalid setting replacement for Marvel exporter

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-migration#76]
Migrating from ES 1.x -> ES 2.x -> ES 5.0.

between ES 1.x -> ES 2.x, the 1.x migration plugin does not throw any errors/warnings/advisory on the marvel.agent.exporter.es.hosts setting.  This was actually changed in ES 2.x (https://www.elastic.co/guide/en/marvel/current/configuration.html) already.  But subsequently the settings are renamed to xpack.monitoring.\* in 5.0 (below).

between ES 2.x -> ES 5.0, the 2.x migration plugin throws the following:

![image](https://cloud.githubusercontent.com/assets/7216393/19372376/5d15da3c-9170-11e6-93a8-27f40b3c7859.png)

But `xpack.monitoring.collection.exporter.es.hosts` above is not a valid setting.   It should be something like (https://www.elastic.co/guide/en/x-pack/current/configuring-monitoring.html#monitoring-cluster):

```
 xpack.monitoring.exporters.<id>.host (required)
 xpack.monitoring.exporters.<id>.type (required)
 xpack.monitoring.exporters.<id>.auth.username (optional if using security)
 xpack.monitoring.exporters.<id>.auth.password (optional if using security)
```

**Comment by clintongormley** [comment]
Closed by #76
