### ISSUE TITLE
Migration plugin recommends invalid setting for Watcher

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-migration#77]
2.x migration plugin recommends incorrect settings for Watcher for 5.0 upgrade:

![image](https://cloud.githubusercontent.com/assets/7216393/19372469/3456f47c-9171-11e6-8cff-46b5d015dbe2.png)

The above are invalid, should be:

```
xpack.notification.email.account.gmail_account.profile
xpack.notification.email.account.gmail_account.smtp.auth
xpack.notification.email.account.gmail_account.smtp.host
xpack.notification.email.account.gmail_account.smtp.port
xpack.notification.email.account.gmail_account.smtp.starttls
xpack.notification.email.account.gmail_account.smtp.user
```

Also, the recommendations are missing the suggested replacement for `watcher.actions.email.service.account.gmail_account.smtp.user`, probably because we don't return password fields in the node settings API.  If so, perhaps we can just automatically add the password setting recommendation for watcher.actions.email.service.account.gmail_account.smtp.user -> xpack.notification.email.account.gmail_account.smtp.password as soon as we detect the presence of the associated user property.

**Comment by clintongormley** [comment]
thanks @ppf2 - i've fixed the rename issue.  As far as not picking up the password setting, this already seems to work for me.  I'll ping you when I have a new build for you to check.

**Comment by clintongormley** [comment]
@ppf2 the new build is available. I'll close this for now. Please open a new issue if there is still a problem
