### ISSUE TITLE
Plugin install vs. URL naming consistency 

### ISSUE THREAD

**Issue by skearns64** [elastic/elasticsearch-migration#8]
With Marvel,  we install: 

```
bin/plugin -i elasticsearch/marvel/latest
```

and have the URL:

```
http://localhost:9200/_plugin/marvel
```

For the migration plugin, it would be good to have the same name for the plugin and the URL. This is a suggestion for naming, but I'm not tied to it. I mainly just like the consistency:

```
bin/plugin -i elasticsearch/migration/latest
http://localhost:9200/_plugin/migration
```

**Comment by clintongormley** [comment]
Closing as won't fix
