### ISSUE TITLE
How to install this plugin with docker?

### ISSUE THREAD

**Issue by tinder-xhao** [elastic/elasticsearch-migration#82]
I have a docker file which will  install elasticsearch for me with the lmenezes/elasticsearch-kopf/1.0 plugin. But when I'm trying to install this migration plugin, it doesn't work. It seems that docker could download the file, but when I'm trying to open the plugin through browser on local server, it doesn't show anything. 

My docker file is configured as following:

```
# Pull base image.
FROM elasticsearch:1.4.5

ADD elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

RUN /usr/share/elasticsearch/bin/plugin -i migration -u https://github.com/elastic/elasticsearch-migration/releases/download/v1.18/elasticsearch-migration-1.18.zip
RUN /usr/share/elasticsearch/bin/plugin -install lmenezes/elasticsearch-kopf/1.0

COPY setup-elasticsearch.sh /
ENTRYPOINT ["/setup-elasticsearch.sh"]
CMD ["elasticsearch"]
```

**Comment by joshuar** [comment]
This plugin should work in Docker.  Is the migration plugin listed in `GET /_cat/plugins` output?  What response do you get back when accessing the migration plugin URL (and what URL are you using)?

**Comment by tinder-xhao** [comment]
I finally got it set up. Is this migration plugin able to check the upgrading from 1.x to 5.x?

**Comment by clintongormley** [comment]
@tinder-xhao no - this is for 2.x to 5.x only
