### ISSUE TITLE
Severity of transform mapping removal should be increased

### ISSUE THREAD

**Issue by nkvoll** [elastic/elasticsearch-migration#87]
It seems like https://github.com/elastic/elasticsearch-migration/blob/2.x/src/migration/Mapping.js#L95 should have severity `red` instead of `yellow`, as the [`transform` mapping](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/mapping-transform.html) has been removed in `5.0` (it was deprecated in `2.0`).

Elasticsearch `5.0.0` is not able to recover an index that uses this feature, and will log an exception and exit.

**Comment by clintongormley** [comment]
Closed by 7df4fdc4452eca73f2170b9ddbca23d6611fa2f0
