### ISSUE TITLE
No way to install

### ISSUE THREAD

**Issue by Ios77** [elastic/elasticsearch-migration#88]
Maybe wrong place to post, but no way to install.
The documentation refer to old deprecated command:

`/opt/logstash/bin/plugin install https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.1/elasticsearch-migration-2.0.1.zip
The use of bin/plugin is deprecated and will be removed in a feature release. Please use bin/logstash-plugin.
Validating https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.1/elasticsearch-migration-2.0.1.zip
Plugin https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.1/elasticsearch-migration-2.0.1.zip does not exist
ERROR: Installation aborted, verification failed for https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.1/elasticsearch-migration-2.0.1.zip`

and the new command:

`/opt/logstash/bin/logstash-plugin install --local  https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.1/elasticsearch-migration-2.0.1.zip
Installing https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.1/elasticsearch-migration-2.0.1.zip
Plugin not found, aborting
ERROR: Installation Aborted, message: Could not find gem 'https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.1/elasticsearch-migration-2.0.1.zip (>= 0) java' in any of the gem sources listed in your Gemfile or installed on this machine.`

How to in install this plugin?????
Thanks a lot,

Ivan

**Comment by dadoonet** [comment]
elasticsearch-migration is an elasticsearch plugin. Not a logstash one.

Please ask questions like this on discuss.elastic.co. We can help there.

**Comment by Ios77** [comment]
Ok thanks sorry,

Ivan
