### ISSUE TITLE
Cluster settings check for deprecated/renamed settings (blue -> yellow)

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-migration#93]
Since blue means no action needed, these checks (eg. persistent cluster settings) should really be depicted as yellow.  Otherwise, they will just be ignored by 5.0+ on startup by default and not take effect on the new cluster.

```
Cluster Settings

    Unknown settingsℹ
        threadpool.bulk.queue_size will be moved to the archived namespace on upgrade
```

**Comment by clintongormley** [comment]
Fixed in ec6765d5a06a2d92b9dec4f9397c1fe25c229535
