### ISSUE TITLE
Migration plugin throws (unknown) error on .security index

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-migration#94]
The .security is a system index that can only be accessed by Shield.  The migration plugin is not handling this and throwing a gray error (unknown error).  Perhaps we can skip this check ..

![image](https://cloud.githubusercontent.com/assets/7216393/19952323/a15356b4-a121-11e6-96b3-5a291ca010b2.png)

**Comment by ppf2** [comment]
It looks like a bigger problem here, once it hits the .security index's unknown gray error, it stops checking the other indices in the cluster.  Clicking on `Show green test results` reviews that it only checked for all the system . indices, and after .security, no other indices (user indices) are checked by the migration plugin.

**Comment by clintongormley** [comment]
Fixed in 046de9463bbaac271e1143f2c791ee4021c3ed90

**Comment by ppf2** [comment]
Thx @clintongormley for the quick fix :)
