### ISSUE TITLE
Send users to xpack guide for xpack setting changes

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-migration#95]
Renamed settings simply link users to the base ES settings breaking changes page.

![image](https://cloud.githubusercontent.com/assets/7216393/20582726/8d582d06-b198-11e6-9bf4-60c477c1ff34.png)

It will be nice to provide different linkages for x-pack settings given that the ES settings breaking change will not have any information on x-pack specific breaking changes.

**Comment by clintongormley** [comment]
Closed by fdc3431f36622192afce00e1fa892b52e5935fbd
