### ISSUE TITLE
File Descriptor limit reported as Fail on Windows

### ISSUE THREAD

**Issue by marius-dr** [elastic/elasticsearch-migration#96]
The plugin reports the File Descriptor limit as a fail even though this doesn't apply on Windows nodes. I think it should be remove the check if the node is Windows based as it makes the upgrade process less of a hassle than it has to be. 
![file_descriptor](https://cloud.githubusercontent.com/assets/5196019/21083265/51e219a6-bff5-11e6-931b-cf17a2424ab4.png)

Noticed on a Windows 10 TH2, with ES 2.4.1.

**Comment by clintongormley** [comment]
thanks @marius-dr - closed by 8a605ae6d99c6fa481511f573dc2628035207c3f
