### ISSUE TITLE
download of v1.19 has nothing inside the zip

### ISSUE THREAD

**Issue by DarrenHart1989** [elastic/elasticsearch-migration#99]
Was getting the following error when trying to install the plugin. 

Ran this command: 

`./bin/plugin -i migration -u https://github.com/elastic/elasticsearch-migration/releases/download/v1.19/elasticsearch-migration-1.19.zip`

Failed with:

`Failed to install migration, reason: failed to rename in order to copy to _site (rename to /usr/share/elasticsearch/plugins/migration.tmp`

Then downloaded the .zip file directly and found that it was actually empty.

**Comment by clintongormley** [comment]
Sorry, should be fixed now
